---
- hosts: all
  become: false

  tasks:

          
      - name: Stop running Service
        command: sudo docker service rm ycesproject
        ignore_errors: yes


    
      - name: Run the new service        
        command: sudo docker service create --replicas 2 -p 80:8083 --name ycesproject 1365890/ycesproject




      - name: Remove all older images
        command: sudo docker image prune -f


     

      

     
      

